### PR TITLE
feat: only save files if they are unchanged

### LINKED ISSUE #320: Skip file write if file content isn't changed
If the input is the same as the output CSS and the `--replace` flag is passed, the file is always overridden. Can we somehow prevent this from happening? 

The issue I have now is that I have another watcher on these files which detect file changes even if the content is not changed.

https://github.com/postcss/postcss-cli/blob/42fc85e743b20dd8d4f3d6a1d16b4de31f7aa08a/index.js#L222-L227

We could wrap these lines with a simple check to prevent the file write from happening:

```javascript
if (result.css !== css.toString('utf8')) {
  tasks.push(fs.outputFile(options.to, result.css))

  if (result.map) {
    const mapfile = getMapfile(options)
    tasks.push(fs.outputFile(mapfile, result.map))
  }
}
```

Not sure if we can better add a new option or do this check by default, what do you think?

### PR DESCRIPTION
**Pull request by kentcdodds**
Closes #320

This also solves a significant annoyance for anyone using postcss with an app that rebuilds on file change: https://github.com/remix-run/remix/issues/714

### CODE REVIEW

**Comment by RyanZim** [comment]
Hey, code looks good; my only concern is performance. Has any testing been done on this?

**Comment by kentcdodds** [comment]
Just did some testing here:

```js
const fs = require("fs-extra");

async function oneFile() {
  console.time("one file");
  await fs.readFile("./files/01.css");
  console.timeEnd("one file");
}

async function hundredFiles() {
  console.time("100 files");
  for (let i = 0; i < 100; i++) {
    await fs.readFile(`./files/01 copy ${i}.css`);
  }
  console.timeEnd("100 files");
}

oneFile();
hundredFiles();
```

Those css files are *each* 111kb of this copy/pasted over and over:

```
body {
  color: red;
}
```

My output (on my fast machine) is:

```
one file: 0.557ms
100 files: 15.627ms
```

It's pretty darn fast. Feel free to watch for yourself (I'm live streaming right now): https://www.youtube.com/watch?v=KPKBUBchCVo

So I think this is fine. Though if you'd like to add an opt-out option then I could do that. But I kinda think that should be some added complexity that we should add only if necessary since this doesn't seem to be much of a problem.

**Comment by RyanZim** [comment]
Hey, sorry for the slowness here; didn't want to merge until I had spare time to publish a new version.

**Comment by kentcdodds** [comment]
No worries. I know life is busy 😅 Thanks for merging and releasing this!

**Comment by chillitom** [comment]
could comparing files sizes first and only reading/comparing if different give a small perf improvement?

**Comment by kentcdodds** [comment]
I expect it could, but it's it really worth the added complexity? For most cases it doesn't even take a full millisecond to just read and compare. It probably wouldn't make much of a difference...

**Pull request merged**
