### PR TITLE
Better Error handling

### LINKED ISSUE #100: Reading from stdin is a normal flow when stdin is not a tty and should not warn
It’s perfectly normal to pipe data to postcss-cli (e.g. in a makefile); that it classifies “no files passed, reading from stdin” as a warning and prints same to the terminal is a bug. There’s no way to indicate that this is the correct and intended behaviour at present (some tools accept `-` as meaning stdin or stdout, as appropriate, but this one doesn’t).

If stdin is a tty, I can understand warning about it. But when it’s not, it *really* shouldn’t produce a warning.

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
fixes #100 , #1

### CODE REVIEW

**Comment by RyanZim** [comment]
@michael-ciniawsky I'm not sure what issues this PR is trying to solve.

---

The only thing blocking the v3 release is that we need to error out if `from` or `to` is set in the config. I'll try to do this myself this afternoon (depends how busy I am).

**Comment by michael-ciniawsky** [comment]
- Prettier Error Formatting
- Bugfix when an error is thrown anf input is STDIN (no err.file)
- README.md fixes

See the two linked issues above

**Comment by michael-ciniawsky** [comment]
I knew it 🤣 .There is no mess 💯 I tested them locally in and out 🤓. Also no crap in the background while watching files, if there are still regressions encountered blame is on me and will fix it 😛

**Comment by michael-ciniawsky** [comment]
The global spinner shouldn't be a problem it does start/stop accurately no inifinte loop like in the initial code for watch mode, which was flanky crap

**Comment by michael-ciniawsky** [comment]
Also if `v3.0.0` is feature complete now in your opinion (the maintainers opinion :godmode: ) just :shipit: bugs && regressions are SemVer patches :)

**Comment by RyanZim** [comment]
OK, if you tested with _multiple files_ in watch mode, I'll let it go.

We still need to error out when `from` or `to` is in the config. I'll fix that tonight if I can.

**Comment by michael-ciniawsky** [comment]
watcherror

**Comment by RyanZim** [comment]
OK, whatever, merging.

**Comment by RyanZim** [comment]
Thanks!

**Comment by RyanZim** [comment]
Now I'll fix up the config, and we'll be good to go!

**Comment by michael-ciniawsky** [comment]
`Config Error: bla bla option.from via CLI arguments blu blub`  for naming consistency 😛

**Comment by RyanZim** [comment]
Yep, makes sense.

**Pull request merged**
