### PR TITLE
Avoid joining void paths by passing cwd to the globber

### PR DESCRIPTION
**Pull request by manuelmazzuola**
fix https://github.com/postcss/postcss-cli/issues/261

### CODE REVIEW

**Comment by RyanZim** [comment]
According to https://github.com/mrmlnc/fast-glob#cwd; the default is already `process.cwd()`, so I'm not seeing what this changes?

**Comment by manuelmazzuola** [comment]
I don't know but without this change postcss-cli doesn't work for me.
I have postcss-cli 6.1.1, node 10.15.0 and fast-glob 2.2.4 :man_shrugging:

**Comment by manuelmazzuola** [comment]
You mentioned `fast-glob` but according to the package.json `postcss-cli` uses `globby` based on `fast-glob`, and look at this diff, commited 5 hours ago: https://github.com/sindresorhus/globby/commit/d80422881de179c23726bbddd02c0402a797186b#diff-168726dbe96b3ce427e7fedce31bb0bcL50

**Comment by RyanZim** [comment]
Trying doing a fresh install of postcss-cli, so you get globby 8.0.2, and see if that fixes your issue. Refs https://github.com/sindresorhus/globby/pull/99#issuecomment-452647305.

**Comment by manuelmazzuola** [comment]
They have fixed so I'll close this one.

**Pull request closed without merging**
