### PR TITLE
Release/v2.5.2

### PR DESCRIPTION
**Pull request by watilde**
Patch version update proposal. I try to add a [CHANGELOG.md](https://github.com/watilde/postcss-cli/blob/f7e75aae4c12db73a209ad9205e7f8f1ac033cbb/CHANGELOG.md) with [keepchangelog](http://keepachangelog.com/) style.

Included PRs
- #12 
- #16 
- #17 

Could please you check this? @pirxpilot

### CODE REVIEW

**Comment by pirxpilot** [comment]
Looks good. I was using [git-extras] `changelog` and `release` tools to release this project before.
Obviously you are welcome to switch to your favorite tool. Just please incorporate/rename existing `History.md` file contents for completeness. (Specifically let's **not** have both `CHANGELOG` and `History.md`)

[git-extras] https://github.com/tj/git-extras

**Comment by watilde** [comment]
Thanks for quick response! I just updated the `History.md` with `git-extras` :)

**Comment by pirxpilot** [comment]
Super. BTW: I hope you're not waiting for an OK from me. I am happy to comment if you ask, but as far as I am concerned you can release this project on your schedule whenever you deem appropriate.

**Comment by watilde** [comment]
Ahh ok, I got it! I will handle this from this night, thanks :)

**Comment by watilde** [comment]
Ok ship it!

**Pull request merged**
