### PR TITLE
Add log option

### PR DESCRIPTION
**Pull request by schoenwaldnils**
I added an option to see when a file is updated/generated.
Sadly the `v` for `verbose` is already used for `version`, so I used `l`for `log`

### CODE REVIEW

**Comment by watilde** [comment]
LGTM

**Comment by RyanZim** [comment]
@schoenwaldnils @watilde Shouldn't this be rebased into one commit?

**Comment by watilde** [comment]
@RyanZim yeah it would be nicer, or I will cherry-pick it like the last release https://github.com/postcss/postcss-cli/pull/19

**Comment by RyanZim** [comment]
@watilde You could also squash-merge it: https://github.com/blog/2141-squash-your-commits.

**Comment by moll** [comment]
I'd like to see this merged in, too, as it's very unclear when PostCSS has finished processing when watching. However, I'd say go with `--verbose` and possibly `-V` if nothing else to be consistent with every other thing. ;-)

**Comment by watilde** [comment]
This PR is shipped as https://github.com/postcss/postcss-cli/commit/90ad9df2d34737d2663f9489e79d6a7f6d1be825. Thanks for making improvements in the new feature!

**Pull request closed without merging**
