### PR TITLE
Get dependency watching working, add test

### PR DESCRIPTION
**Pull request by RyanZim**

### CODE REVIEW

**Comment by RyanZim** [comment]
I think something is wrong with this, will investigate.

**Comment by michael-ciniawsky** [comment]
I'm on mobile right now, we could in general split the codebase into their own modules `processCSS` `processFiles`, after the PR here could you hold own a bit so I can take a deeper look a everything today please ? :)

**Comment by RyanZim** [comment]
@michael-ciniawsky Watch tests are failing randomly, this PR still needs work.

I'll think about modularization, currently we are relying on the global config var, but that may change with https://github.com/postcss/postcss-cli/issues/72.

> after the PR here could you hold on a bit so I can review and test everything please ? 

I'm not a guy that likes to stop working, but...maybe. :wink:

**Comment by RyanZim** [comment]
@michael-ciniawsky I can't see anything wrong with the code or the tests, but all of the watch tests fail randomly on Travis and locally. I suspect the tests are just flaky, so just have to live with it. (Unless you find the problem, of course)

**Comment by RyanZim** [comment]
Anyhow, I'd be ready to merge this.

**Comment by michael-ciniawsky** [comment]
@RyanZim Yep merge, please so I take a look at status quo today 😛

**Comment by RyanZim** [comment]
@michael-ciniawsky Merged.

**Comment by RyanZim** [comment]
@michael-ciniawsky I'm itching to get to work on postcss-cli, tell me when you've caught up! :laughing:

**Pull request merged**
